config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :inventories
  resources :warehouses, only: [:new, :create, :index, :show]
  resource :employees, only: [:create, :new]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  root "inventories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, :employee_id, presence: true
  validates :employee_id, uniqueness: true

  has_secure_password
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :part
  belongs_to :order
  validates :part, presence: true, uniqueness: { scope: :order }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :part
  belongs_to :warehouse

  def global_count
    Inventory.where(part_id: self.part_id).count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :entries
  belongs_to :warehouse
  accepts_nested_attributes_for :entries
  def add_entry(args)
    part = Part.find_by(number: args[:number])
    if part
      create_entry(part, args[:ordered_quantity])
    else
      part = Part.create(name: args[:name], number: args[:number])
      create_entry(part, args[:ordered_quantity])
    end
  end

  private

  def create_entry(part, quantity)
    Entry.create(order: self, part: part, ordered_quantity: quantity.to_i)
  end
end

app/models/part.rb
class Part < ApplicationRecord
  has_many :inventories
  has_many :warehouses, through: :inventories
  has_many :entries
  validates :name, presence: true
  validates :number, presence: true, uniqueness: true

  def local_count(location)
    warehouse = Warehouse.find_by(name: location)
    parts = warehouse.parts
    parts_with_same_name = parts.where(name: self.name)
    parts_with_same_name.count
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  has_many :inventories
  has_many :parts, through: :inventories
  has_many :orders

  validates :name, presence: true, uniqueness: true


  def inventory
    @inventory = self.parts.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_employee
    @current_employee ||= Employee.find(session[:employee_id]) if session[:employee_id]
  end
  helper_method :current_employee

  def authorize
    redirect_to '/login' unless current_employee
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:notice] = ["You have successfully added new employee, #{@employee.name}."]
      @employee
    else
      flash[:alert] = @employee.errors.full_messages
    end
  end

  def new
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :employee_id, :password, :admin)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authorize
  def index
    @inventory = Inventory.all.uniq {|entry| entry.part_id}
  end

  def new
    @order = Order.find[params[:id]]
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    location = Warehouse.find(receive_params['location'])
    receive_params.each do |entry_id, entry|
      if entry['receive'] == 'yes'
        entry['qty'].to_i.times do
          location.parts << Entry.find(entry_id).part
        end
      end
    end
    redirect_to warehouses_path
  end

  private

  def receive_params
    params.require(:entry).permit!
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def new
    @warehouse = Warehouse.all
  end

  def create
    warehouse = Warehouse.find_by(name: order_params['name'])
    @order = Order.create(warehouse: warehouse)
    redirect_to order_path(@order)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if params[:commit] == "Submit Order"
      @order.submitted = true
      @order.save
    else
      @order.add_entry(entry_params)
    end
    redirect_to order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:name)
  end

  def entry_params
    params.require(:entry).permit(:name, :number, :ordered_quantity)
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    employee = Employee.find_by_employee_id(employee_params[:employee_id])
    if employee && employee.authenticate(employee_params[:password])
      session[:employee_id] = employee.id
      flash[:notice] = ["You have successfully logged in."]
      redirect_to '/'
    else
      flash[:alert] = ["Your employee ID or password combination are incorrect."]
      redirect_to '/login'
    end
  end

  def destroy
    session[:employee_id] = nil
    flash[:notice] = ["You have successfully logged out."]
    redirect_to '/login'
  end

  private
  def employee_params
    params.require(:employee).permit(:employee_id, :password)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :authorize
  def index
    @warehouses = Warehouse.all
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save
      flash[:notice] = ["You have successfully added new warehouse in #{@warehouse.name}."]
      redirect_to warehouses_path
    else
      flash[:alert] = @warehouse.errors.full_messages
    end
  end


  def show
    @inventory = Warehouse.find(params[:id]).parts.uniq
  end

  private
  def warehouse_params
    params.require(:warehouse).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/employees/new.html.erb
<div class="register-container">
  <%= form_for :employee, html: { class: "employee-input" }, url: employees_path do |f| %>
    <h2>Register an Employee</h2>
    <%= f.text_field :name, placeholder: "name " %>
    <%= f.text_field :employee_id, placeholder: "employee id" %>
    <%= f.password_field :password, placeholder: "password" %>
    <%= f.submit 'Add Employee', class: "submit-class-name-here" %>
  <% end %>
</div>

app/views/employees/show.html.erb
<!-- <h1>Welcome, <%= @employee.name %>! </h1> -->

app/views/inventories/edit.html.erb
<div class="order-form">


<h3>Order #<%= @order.id %></h3>
<h4>Location: <%= @order.warehouse.name %></h4>
<table class="inventory-table">
  <tr>
      <th>Part Name</th>
      <th>Part Number</th>
      <th>Quantity Ordered</th>
      <th>Quantity Received</th>
      <th>Quantity to Receive</th>
      <th>Receive</th>
  </tr>
  <form class="receive_order" action="/inventories/update" method="post">
    <input type="hidden" name="_method" value="put">
    <input type="hidden" name="entry[location]" value="<%= @order.warehouse.id %>">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    <% @order.entries.each do |entry| %>
      <tr class="inventory-tr">
          <th class="inventory-th"><%= entry.part.name %></th>
          <th class="inventory-th"><%= entry.part.number %></th>
          <th class="inventory-th"><%= entry.ordered_quantity %></th>
          <th class="inventory-th"><%= entry.received_quantity %></th>

          <th class="inventory-th"><input type="text" name="entry[<%= entry.id %>][qty]" value="<%= entry.ordered_quantity - entry.received_quantity %>"></th>

          <th class="inventory-th"><input type="checkbox" name="entry[<%= entry.id %>][receive]" value="yes"></th>
      </tr>
    <% end %>
    <input type="submit" name="" value="Receive Order">
  </form>
</table>
</div>

app/views/inventories/index.html.erb
<div class="clipboard">
  <div class="list-container">
    <h2 class="warehouse-index-header">Inventory</h2>

    <table class="inventory-table">
      <tr class="header-row">
          <th class="header-th">Part Name</th>
          <th class="header-th">Part Number</th>
          <th class="header-th">Quantity</th>
      </tr>
      <% @inventory.each do |entry| %>
        <tr class="inventory-tr">
          <th class="inventory-th"><%= entry.part.name %></th>
          <th class="inventory-th"><%= entry.part.number %></th>
          <th class="inventory-th"><%= entry.global_count %></th>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/inventories/new.html.erb
<div class="order-form">


<% @order.entries.each do |entry| %>
  <form class="" action="index.html" method="post">
    <span> <%= entry.part.number %> </span>
    <span> <%= entry.part.name %> </span>
    <input type="text" name="quantity[<%= entry.part.number %>]" value="entry.ordered_quantity">
    <input type="checkbox" name="confirm[<%= entry.part.number %>]">
  </form>
  <% end %>
</div>

app/views/orders/_form_qty.html.erb
<form class="" action="index.html" method="post">

</form>

app/views/orders/index.html.erb
<div class="order-form">



<% @orders.each do |order| %>
  <h4><%= link_to "order ##{order.id}", order %></h4>
<% end %>
</div>

app/views/orders/new.html.erb
<div class="clipboard">
  <div class="order-container">
  <h2>Place an Order</h2>
  <div class="list-container">
<%= form_for :order, url: orders_path do |f| %>
  <label for="">Warehouse Location:</label>
  <%= f.collection_select :name, @warehouse, :name, :name %>
  <%= f.submit 'Start Order' %>
<% end %>
  </div>
  </div>
</div>

app/views/orders/show.html.erb
<% if @order.submitted == true %>
<div class="order-form">


<h3>Order #<%= @order.id %> </h3>
<h4>Location: <%= @order.warehouse.name %></h4>
<table class="inventory-table">
  <tr>
      <th>Part Name</th>
      <th>Part Number</th>
      <th>Quantity</th>
  </tr>
  <% @order.entries.each do |entry| %>
    <tr class="inventory-tr">
      <th class="inventory-th"><%= entry.part.name %></th>
      <th class="inventory-th"><%= entry.part.number %></th>
      <th class="inventory-th"><%= entry.ordered_quantity %></th>
    </tr>
  <% end %>
</table>

<%= link_to 'receive order', edit_inventory_url %>
</div>
<% else %>

<div class="clipboard">
  <div class="order-container">

    <h2>Add an Entries</h2>


  <div class="list-container">

  <% if @order.submitted == false %>
    <% if @order.entries.length > 0 %>
      <table class="inventory-table">
        <tr class="header-row">
            <th class="header-th">Part Name</th>
            <th class="header-th">Part Number</th>
            <th class="header-th">Quantity</th>
        </tr>
        <% @order.entries.each do |entry| %>
        <tr class="inventory-tr">
          <th class="inventory-th"><%= entry.part.name %></th>
          <th class="inventory-th"><%= entry.part.number %></th>
          <th class="inventory-th"><%= entry.ordered_quantity %></th>
        </tr>
        <% end %>
      </table>
      <% end %>
    <%= form_for :entry, url: order_path(@order), method: (:put), html: { class: "order-form" } do |f| %>
      <label for="">Part Name:</label>
      <%= f.text_field :name %>
      <label for="">Part Number:</label>
      <%= f.text_field :number %>
      <label for="">Count:</label>
      <%= f.number_field :ordered_quantity %>
      <%= f.submit 'Add to Order' %>
      <%= f.submit 'Submit Order' %>
    <% end %>
  <% end %>

  <% if @order.submitted %>
    <h3>Order #<%= @order.id %> </h3>
    <p><%= @order.warehouse.name %></p>
    <% @order.entries.each do |entry| %>
      <ul>
        <li><%= entry.part.name %> - <%= entry.ordered_quantity %> </li>
      </ul>
    <% end %>
  <% end %>
  </div>
  </div>
</div>
<% end %>

app/views/warehouses/_show.html.erb
  <table class="inventory-table">
    <tr class="header-row">
        <th class="header-th">Part Name</th>
        <th class="header-th">Part Number</th>
        <th class="header-th">Quantity</th>
    </tr>
    <% inventory.each do |part| %>
      <tr class="inventory-tr">
        <th class="inventory-th"><%= part.name %></th>
        <th class="inventory-th"><%= part.number %></th>
        <th class="inventory-th"><%= part.local_count(location) %></th>
      </tr>
    <% end %>
  </table>

app/views/warehouses/index.html.erb
<div class="clipboard">
  <div class="list-container">
    <div class="h2-container">
      <h2 class="warehouse-index-header">Inventory By Warehouse</h2>
    </div>
      <div class="new-warehouse-div">
        <%= link_to "Add New Warehouse",{ action: "new"}, :class => 'new-warehouse-link' %>
      </div>
    <% @warehouses.each do |warehouse| %>
    <div class="warehouse-container">
      <h3 class="warehouse-index-header"><%= warehouse.name %></h2>
        <%= render partial: "show", layout: false, locals: { inventory: warehouse.inventory, location: warehouse.name } %>
    </div>
    <% end %>

</div>
</div>

app/views/warehouses/new.html.erb
<div class="clipboard">
  <div class="order-container">
  <h2>Create a New Warehouse</h2>
  <div class="list-container">
  <%= form_for :warehouse, method: (:post), url: warehouses_path do |f| %>
    <label for="">Warehouse Location:</label>
    <%= f.text_field :name%>
    <%= f.submit 'Create Warehouse' %>
  <% end %>
  </div>
  </div>
</div>

app/views/warehouses/show.html.erb
<div class="list-container warehouse-container">
  <h2 class="warehouse-index-header">Inventory</h2>

  <table class="inventory-table">
    <tr>
        <th>Part Name</th>
        <th>Part Number</th>
        <th>Quantity</th>
    </tr>
    <% @inventory.each do |part| %>
      <tr class="inventory-tr">
        <th class="inventory-th"><%= part.name %></th>
        <th class="inventory-th"><%= part.number %></th>
        <th class="inventory-th"><%= part.global_count %></th>
      </tr>
    <% end %>
  </table>
</div>